# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lightning.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from regex import W


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 416)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background: rgb(40, 42, 54);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 220, 401, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    color: #44475a;\n"
"}\n"
"QScrollBar:vertical {\n"
"     border: 2px solid grey;\n"
"     background:#ff79c6;\n"
"     color: #f8f8f2;\n"
"     width: 18px;\n"
"     margin: 22px 0 22px 0;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: white;\n"
"     min-height: 20px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: 2px solid grey;\n"
"     background: #ff79c6;\n"
"     height: 20px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }")
        self.textBrowser.setObjectName("textBrowser")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 60, 401, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.radioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color: rgb(248, 248, 242)")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox QAbstractItemView {\n"
"  border: 1px solid grey;\n"
"  background: rgb(40, 42, 54);\n"
"  selection-background-color: rgb(40, 42, 54);\n"
"}\n"
"QComboBox {\n"
" /* border: 2px solid #ff79c6;*/\n"
"  baclground: #282a36;\n"
"  color: #ff79c6;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.radioButton_2 = QtWidgets.QRadioButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color: rgb(248, 248, 242)")
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButton_2)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #44475a;\n"
"color: #f8f8f2;\n"
"}\n"
"QPushButton:disabled {\n"
"color: #6272a4;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ff79c6;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #ff79c6;")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 26))
        self.menubar.setStyleSheet("color: rgb(248, 248, 242)")
        self.menubar.setObjectName("menubar")
        self.menuabout = QtWidgets.QMenu(self.menubar)
        self.menuabout.setObjectName("menuabout")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAppearance = QtWidgets.QAction(MainWindow)
        self.actionAppearance.setObjectName("actionAppearance")
        self.actionAnki = QtWidgets.QAction(MainWindow)
        self.actionAnki.setObjectName("actionAnki")
        self.menuabout.addAction(self.actionAppearance)
        self.menuabout.addAction(self.actionAnki)
        self.menubar.addAction(self.menuabout.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Game2Text"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "Window"))
        self.comboBox.setItemText(0, _translate("MainWindow", "cmd.exe"))
        self.radioButton_2.setText(_translate("MainWindow", "Region"))
        self.pushButton.setText(_translate("MainWindow", "Select"))
        self.label.setText(_translate("MainWindow", "Capture Mode"))
        self.label_2.setText(_translate("MainWindow", "Logs"))
        self.menuabout.setTitle(_translate("MainWindow", "Settings"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAppearance.setText(_translate("MainWindow", "Appearance"))
        self.actionAnki.setText(_translate("MainWindow", "Anki"))

# if __name__ == "__main__":
#         import sys
#         app = QtWidgets.QApplication(sys.argv)
#         window = QtWidgets.QMainWindow()
#         ui = Ui_MainWindow()
#         ui.setupUi(window)
#         window.show()
#         sys.exit(app.exec())